### ISSUE TITLE
Application crashes when playing lifeline sound cues 

### ISSUE THREAD

**Issue by Ep1cSpartan** [Macronair/TheMillionaireGame#54]
I noticed that the application crashes when playing certain lifelines like double dip or Plus One. It happens when the audio cues change. I cannot reproduce it a 100% of the time but it happens regularly. I tested it on several machines, reinstalled .NET Framework and tried a fresh virtual machine to verify. The error messages in the Windows Eventlog are as follows:

```
Application: MillionaireGame.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at WMPLib.WindowsMediaPlayerClass.get_controls()
   at MillionaireGame.Sounds.StopAudio(System.String, Int32)
   at MillionaireGame.Question+_Closure$__._Lambda$__10-0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
If you need any other logs, I'd be happy to collect. Simply tell me where to look or if I have to enable some sort of debug or verbose log.
```
Faulting application name: MillionaireGame.exe, version: 1.1.663.0, time stamp: 0x655bda9f
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1413, time stamp: 0xac6c9125
Exception code: 0xe0434352
Fault offset: 0x00147922
Faulting process ID: 0x0x6DE0
Faulting application start time: 0x0x1DA1CA0896E8776
Faulting application path: C:\Apps\MillionaireGame_v1.1.663\MillionaireGame.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 3099f9ac-c34f-49f4-96ac-14b856ee0c3e
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Ep1cSpartan** [comment]
This also happens with the latest build 1.1.671

```
Faulting application name: MillionaireGame.exe, version: 1.1.671.0, time stamp: 0x655d2685
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1413, time stamp: 0xac6c9125
Exception code: 0xe0434352
Fault offset: 0x00147922
Faulting process ID: 0x0x2260
Faulting application start time: 0x0x1DA1D096BB57D82
Faulting application path: C:\Apps\MillionaireGame_v1.1.671\MillionaireGame.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 5ae29f96-06b2-417c-a3f6-d18c733e05a3
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Ep1cSpartan** [comment]
I tested it in several ways, it happens when Plus One / Double Dip are played as first lifeline but it also happened to me when I did a 50:50 first and then the Plus One.
